PUT http://localhost:8080/store
Content-Type: application/json

{
  "id": 2,
  "name": "수정이름",
  "storeAddr": "수정주소",
  "summary": "수정설명",
  "pictureUrl": "수정url",
  "commission": 3.3,
  "deliveryDistanceKm": 4.4,
  "deliveryTip": 5000
}

###